CREATE_INTERVALS = '''
CREATE TABLE IF NOT EXISTS Intervals (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  ChatId INTEGER,
  Hour INTEGER,
  Minute INTEGER
)
'''

CREATE_READS = '''
CREATE TABLE IF NOT EXISTS Reads (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  ChatId INTEGER,
  JokeId INTEGER 
)
'''

CREATE_JOKES = '''
CREATE TABLE IF NOT EXISTS Jokes (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Body TEXT
)
'''

GET_AMOUNT_JOKES = '''
SELECT COUNT(*) from Jokes 
'''